FROM golang:1.24.8-alpine AS build
ARG MINIO_VERSION=RELEASE.2025-10-15T17-29-55Z
RUN apk add --no-cache git ca-certificates build-base
WORKDIR /src
RUN git clone --depth 1 --branch "${MINIO_VERSION}" https://github.com/minio/minio.git .
RUN LDFLAGS="$(go run buildscripts/gen-ldflags.go)" && \
    CGO_ENABLED=0 go build -tags kqueue -trimpath --ldflags "$LDFLAGS" -o /out/minio .

FROM alpine:3.22
RUN apk add --no-cache ca-certificates && \
    addgroup -S minio && adduser -S -G minio minio && \
    mkdir -p /data && chown -R minio:minio /data
COPY --from=build /out/minio /usr/local/bin/minio
COPY --from=build /src/LICENSE /licenses/LICENSE
USER minio
WORKDIR /data
EXPOSE 9000 9001
ENTRYPOINT ["minio"]
CMD ["server","/data","--console-address",":9001"]
