#!/usr/bin/env bash
set -Eeuo pipefail

: "${FORGEJO_URL:?Set FORGEJO_URL, e.g. https://git.example.com}"
: "${FORGEJO_RUNNER_TOKEN:?Set FORGEJO_RUNNER_TOKEN generated by scripts/forgejo-runner-token.sh}"

RUNNER_VERSION="${RUNNER_VERSION:-13.1.0}"
RUNNER_NAME="${RUNNER_NAME:-ci-01}"
RUNNER_LABEL="${RUNNER_LABEL:-docker:docker://node:22-bookworm}"
FORGEJO_URL="${FORGEJO_URL%/}"
KEY_FINGERPRINT="EB114F5E6C0DC2BCDD183550A4B61A2DC5923710"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this installer as root on a dedicated CI machine." >&2
  exit 1
fi

for cmd in curl gpg git docker systemctl useradd usermod; do
  command -v "${cmd}" >/dev/null 2>&1 || {
    echo "Missing required command: ${cmd}" >&2
    exit 1
  }
done

docker version >/dev/null 2>&1 || {
  echo "Docker must be installed and running before installing Forgejo Runner." >&2
  exit 1
}

arch="$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"
case "${arch}" in
  amd64|arm64) ;;
  *) echo "Unsupported architecture: ${arch}" >&2; exit 1 ;;
esac

tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

binary_url="https://code.forgejo.org/forgejo/runner/releases/download/v${RUNNER_VERSION}/forgejo-runner-${RUNNER_VERSION}-linux-${arch}"
curl --fail --location --proto '=https' --tlsv1.2 "${binary_url}" -o "${tmp}/forgejo-runner"
curl --fail --location --proto '=https' --tlsv1.2 "${binary_url}.asc" -o "${tmp}/forgejo-runner.asc"

gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "${KEY_FINGERPRINT}"
gpg --batch --verify "${tmp}/forgejo-runner.asc" "${tmp}/forgejo-runner"

install -m 0755 "${tmp}/forgejo-runner" /usr/local/bin/forgejo-runner

if ! id runner >/dev/null 2>&1; then
  useradd --create-home --shell /usr/sbin/nologin runner
fi
usermod -aG docker runner

install -d -o runner -g runner -m 0700 /home/runner
if [ ! -f /home/runner/runner-config.yml ]; then
  runuser -u runner -- /usr/local/bin/forgejo-runner generate-config > /home/runner/runner-config.yml
  chown runner:runner /home/runner/runner-config.yml
  chmod 0600 /home/runner/runner-config.yml
fi

rm -f /home/runner/.runner

runuser -u runner -- sh -lc "
  cd /home/runner
  /usr/local/bin/forgejo-runner register     --no-interactive     --instance '${FORGEJO_URL}'     --token '${FORGEJO_RUNNER_TOKEN}'     --name '${RUNNER_NAME}'     --labels '${RUNNER_LABEL}'
"

cat > /etc/systemd/system/forgejo-runner.service <<'EOF'
[Unit]
Description=Forgejo Actions Runner
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=simple
User=runner
Group=runner
SupplementaryGroups=docker
WorkingDirectory=/home/runner
ExecStart=/usr/local/bin/forgejo-runner daemon -c /home/runner/runner-config.yml
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=read-only
ProtectSystem=strict
ReadWritePaths=/home/runner
LockPersonality=true
RestrictSUIDSGID=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now forgejo-runner

echo "Forgejo Runner ${RUNNER_VERSION} installed."
echo "Runner: ${RUNNER_NAME}"
echo "Label:  ${RUNNER_LABEL}"
echo "Check:  systemctl status forgejo-runner"
echo "Logs:   journalctl -u forgejo-runner -f"
